### ISSUE TITLE
require at least one switch [out of a group of switches]

### ISSUE THREAD

**Issue by ywen** [picklepumpers/pickled_optparse#1]
OK, what about,say, I have two switches, but I require one and only one? Do you think of handling this situation?

**Comment by picklepumpers** [comment]
Yes, this handles that situation. You only use the required indicator on switches that are required. If you don't use the required indicator on a switch then it's not required. Simple as that.

Take a look at the example file, it has a bunch of required switches and one non-required switch: https://github.com/picklepumpers/pickled_optparse/blob/master/examples/example.rb

**Comment by ywen** [comment]
Thanks for replying. Although I am not sure what you mean. My original question was if I can require at least one switch, but not limited to which one. For example, I have 2 switches: -s and -i, The user has to specify at least one, be it -i or -s, but not both. So it's more like: :require => [-s, -i]. THanks again!

**Comment by picklepumpers** [comment]
Ah, your original question wasn't very clear. I've edited the title to make it a little more clear.

This version does not support required groups but I'm literally working right now on a completely original command line option parser that does support this kind of functionality. 

But don't hold your breath; it will probably take quite a while because I'm still very new to Ruby so as I write the meta project I keep finding libraries I want to develop just to learn more instead of taking the easy route and using libraries that already exist.
